spring:
  thymeleaf:
    prefix: classpath:templates/
    mode: HTML
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:~/conquercrux;AUTO_SERVER=TRUE
    username: sa
    password:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

mybatis:
  mapper-locations: mapper/**/*.xml

logging:
  charset:
    console: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - %msg%n"
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    jdbc:
      audit: WARN
      connection: WARN
      resultset: WARN
      resultsettable: INFO
      sqlonly: OFF
      sqltiming: INFO

jwt:
  token:
    secret: "secretKey"

server:
  servlet:
    session:
      timeout: 1800 # 세션 유효 시간을 초 단위로 설정합니다 (예: 1800초 = 30분)
